export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف وجبة الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف وجبة غداء",
    price: "50 جنيه",
    category: "غداء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف وجبة الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف وجبة الفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف وجبة الفطار",
    price: "50 جنيه",
    category: "غداء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف وجبة الفطار",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
];
